set nocompatible

filetype plugin indent on

" Editing
set ignorecase

" Display
set background=dark
set cursorline
set hlsearch
set incsearch
set laststatus=2
set noshowmode
set number
set relativenumber
set ruler
set shortmess-=S
set termguicolors
set visualbell
syntax enable

" Indentation
set autoindent
set expandtab
set shiftwidth=2
set smarttab
set softtabstop=2
set tabstop=2

" Packages
packadd! onedark.vim
colorscheme onedark

packadd! lightline.vim
let g:lightline = { 'colorscheme': 'one' }
